# Generated by Django 3.2.6 on 2023-02-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booksdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=50)),
                ('average_rating', models.FloatField()),
                ('isbn', models.IntegerField()),
                ('language_code', models.CharField(max_length=10)),
                ('num_pages', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('text_reviews_count', models.IntegerField()),
                ('publication_date', models.DateField()),
                ('publisher', models.CharField(max_length=100)),
                ('bookshelf_number', models.CharField(max_length=2)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
