# Generated by Django 3.2.6 on 2023-02-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksdata',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='booksdata',
            name='level',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
