# Generated by Django 3.2.6 on 2023-03-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230226_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksdata',
            name='authors',
            field=models.CharField(max_length=540),
        ),
        migrations.AlterField(
            model_name='booksdata',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='booksdata',
            name='language_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='booksdata',
            name='level',
            field=models.PositiveSmallIntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='booksdata',
            name='num_pages',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='booksdata',
            name='publication_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booksdata',
            name='publisher',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='booksdata',
            name='ratings_count',
            field=models.IntegerField(max_length=7),
        ),
        migrations.AlterField(
            model_name='booksdata',
            name='text_reviews_count',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='booksdata',
            name='title',
            field=models.CharField(max_length=210),
        ),
    ]
