# Generated by Django 3.2.6 on 2023-03-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230301_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksdata',
            name='available',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='booksdata',
            name='level',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='booksdata',
            name='num_pages',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booksdata',
            name='ratings_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booksdata',
            name='text_reviews_count',
            field=models.IntegerField(),
        ),
    ]
