# Generated by Django 3.2.6 on 2023-03-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='abc',
            new_name='Borrowed_bookdata',
        ),
    ]
